# Generated by Django 6.0.6 on 2026-06-29 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroPrevisional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(verbose_name='Mes de remuneración')),
                ('fuente', models.CharField(choices=[('previred', 'PreviRed'), ('sii', 'SII'), ('manual', 'Manual')], default='previred', max_length=20)),
                ('valor_uf', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_utm', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sueldo_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tope_imponible_afp', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tope_imponible_ips', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tope_imponible_seg_ces', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tasa_fonasa', models.DecimalField(decimal_places=4, default=7, max_digits=6)),
                ('tasa_afc_trabajador', models.DecimalField(decimal_places=4, default=0.6, max_digits=6)),
                ('tasa_afc_empresa_indefinido', models.DecimalField(decimal_places=4, default=2.4, max_digits=6)),
                ('tasa_afc_empresa_plazofijo', models.DecimalField(decimal_places=4, default=3.0, max_digits=6)),
                ('tasa_afc_empresa_11anos', models.DecimalField(decimal_places=4, default=0.8, max_digits=6)),
                ('tasa_afc_empresa_casaparticular', models.DecimalField(decimal_places=4, default=3.0, max_digits=6)),
                ('tasa_sis', models.DecimalField(decimal_places=4, default=1.62, max_digits=6)),
                ('tasa_seguro_social', models.DecimalField(decimal_places=4, default=0.9, max_digits=6)),
                ('tope_gratificacion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tope_sueldo_gratificacion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hash_checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetro Previsional',
                'verbose_name_plural': 'Parámetros Previsionales',
                'ordering': ['-mes'],
            },
        ),
        migrations.CreateModel(
            name='TasaAFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tasa_cotizacion', models.DecimalField(decimal_places=4, max_digits=6)),
                ('tasa_sis', models.DecimalField(decimal_places=4, max_digits=6)),
                ('tasa_total', models.DecimalField(decimal_places=4, max_digits=6)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tasa AFP',
                'verbose_name_plural': 'Tasas AFP',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TramoImpuestoUnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde_utm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hasta_utm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('factor', models.DecimalField(decimal_places=4, max_digits=6)),
                ('rebaja_utm', models.DecimalField(decimal_places=4, max_digits=10)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tramo Impuesto Único',
                'verbose_name_plural': 'Tramos Impuesto Único',
                'ordering': ['desde_utm'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionVoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistente_activado', models.BooleanField(default=False)),
                ('respuestas_voz', models.BooleanField(default=False)),
                ('notificacion_whatsapp', models.BooleanField(default=False)),
                ('numero_whatsapp_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('idioma', models.CharField(default='es-CL', max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_voz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Voz',
                'verbose_name_plural': 'Configuraciones de Voz',
            },
        ),
        migrations.CreateModel(
            name='CambioParametroLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_cambiado', models.CharField(max_length=50)),
                ('valor_anterior', models.CharField(max_length=100)),
                ('valor_nuevo', models.CharField(max_length=100)),
                ('revisado', models.BooleanField(default=False)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculo_sueldo.parametroprevisional')),
            ],
            options={
                'verbose_name': 'Cambio de Parámetro',
                'verbose_name_plural': 'Cambios de Parámetros',
                'ordering': ['-created_at'],
            },
        ),
    ]
