# Generated by Django 6.0.6 on 2026-06-29 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo_sueldo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT Empresa')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('nombre_representante', models.CharField(max_length=255, verbose_name='Representante Legal')),
                ('rut_representante', models.CharField(max_length=12, verbose_name='RUT Representante')),
                ('actividad_economica', models.CharField(max_length=255, verbose_name='Actividad Económica')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('clave_sii_empresa', models.CharField(max_length=255, verbose_name='Clave SII Empresa')),
                ('clave_sii_persona', models.CharField(max_length=255, verbose_name='Clave SII Persona Natural')),
                ('contacto_telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('contacto_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('clave_previred', models.CharField(max_length=255, verbose_name='Clave PreviRed')),
                ('clave_mutual', models.CharField(max_length=255, verbose_name='Clave Mutual')),
                ('clave_afc', models.CharField(max_length=255, verbose_name='Clave AFC')),
                ('clave_portuaria', models.CharField(blank=True, max_length=255, verbose_name='Clave Portuaria')),
                ('clave_unica', models.CharField(max_length=255, verbose_name='ClaveÚnica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='RelacionMandante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_mandante', models.CharField(max_length=12, verbose_name='RUT Mandante')),
                ('razon_social_mandante', models.CharField(max_length=255, verbose_name='Razón Social Mandante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandantes', to='calculo_sueldo.empresa')),
            ],
            options={
                'verbose_name': 'Relación Mandante',
                'verbose_name_plural': 'Relaciones Mandantes',
                'ordering': ['razon_social_mandante'],
                'unique_together': {('empresa', 'rut_mandante')},
            },
        ),
    ]
