# Generated by Django 6.0.6 on 2026-06-29 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo_sueldo', '0002_empresa_relacionmandante'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCarnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_trabajador', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('firma_digital', models.TextField(blank=True, verbose_name='Firma digitalizada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento Carnet',
                'verbose_name_plural': 'Documentos Carnet',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre plantilla')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('funciones', models.TextField(verbose_name='Funciones del cargo')),
                ('clausulas', models.TextField(blank=True, verbose_name='Cláusulas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Contrato',
                'verbose_name_plural': 'Plantillas de Contrato',
                'ordering': ['cargo'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('indefinido', 'Indefinido'), ('plazo_fijo', 'Plazo Fijo'), ('faena', 'Por Faena'), ('part_time', 'Jornada Parcial')], max_length=20, verbose_name='Tipo de contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_termino', models.DateField(blank=True, null=True, verbose_name='Fecha de término')),
                ('nombre_faena', models.CharField(blank=True, max_length=255, verbose_name='Nombre de la Faena')),
                ('rut_trabajador', models.CharField(max_length=12, verbose_name='RUT Trabajador')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('funciones', models.TextField(verbose_name='Naturaleza de servicios / funciones')),
                ('lugar_trabajo', models.CharField(max_length=255, verbose_name='Lugar de trabajo')),
                ('horas_semanales', models.PositiveIntegerField(default=45, verbose_name='Horas semanales')),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sueldo base $')),
                ('colacion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Colación $')),
                ('movilizacion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Movilización $')),
                ('periodicidad_pago', models.CharField(default='mensual', max_length=20, verbose_name='Periodicidad pago')),
                ('clausulas_adicionales', models.TextField(blank=True, verbose_name='Cláusulas adicionales')),
                ('pdf_generado', models.TextField(blank=True, verbose_name='PDF generado (base64)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='calculo_sueldo.empresa')),
                ('mandante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='calculo_sueldo.relacionmandante')),
                ('carnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculo_sueldo.documentocarnet')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculo_sueldo.plantillacontrato')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnexoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clausula_modificada', models.CharField(max_length=255, verbose_name='Cláusula a modificar')),
                ('nuevo_texto', models.TextField(verbose_name='Nuevo texto de la cláusula')),
                ('pdf_generado', models.TextField(blank=True, verbose_name='PDF generado (base64)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='calculo_sueldo.contrato')),
            ],
            options={
                'verbose_name': 'Anexo de Contrato',
                'verbose_name_plural': 'Anexos de Contrato',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PactoHorasExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('renovado', models.BooleanField(default=False, verbose_name='Renovado automáticamente')),
                ('pdf_generado', models.TextField(blank=True, verbose_name='PDF generado (base64)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pactos_horas_extra', to='calculo_sueldo.contrato')),
            ],
            options={
                'verbose_name': 'Pacto Horas Extra',
                'verbose_name_plural': 'Pactos Horas Extra',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
