# Generated by Django 6.0.6 on 2026-06-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo_sueldo', '0003_documentocarnet_plantillacontrato_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pactohorasextra',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='pactohorasextra',
            name='alerta_enviada',
            field=models.BooleanField(default=False, verbose_name='Alerta enviada'),
        ),
        migrations.AddField(
            model_name='pactohorasextra',
            name='numero_renovacion',
            field=models.PositiveIntegerField(default=0, verbose_name='N° renovación'),
        ),
    ]
