# Generated by Django 6.0.6 on 2026-06-29 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo_sueldo', '0004_pactohorasextra_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contrato_vencer', 'Contrato próximo a vencer'), ('contrato_vencido', 'Contrato vencido'), ('pacto_vencer', 'Pacto HE próximo a vencer'), ('pacto_vencido', 'Pacto HE vencido'), ('parametro_desactualizado', 'Parámetro previsional desactualizado'), ('parametro_cambio', 'Cambio en parámetro previsional')], max_length=30, verbose_name='Tipo')),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID referencia')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='Email enviado')),
                ('whatsapp_enviado', models.BooleanField(default=False, verbose_name='WhatsApp enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='calculo_sueldo.empresa')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notificar', models.EmailField(blank=True, max_length=254, verbose_name='Email para notificaciones')),
                ('whatsapp_activo', models.BooleanField(default=False, verbose_name='WhatsApp activo')),
                ('whatsapp_numero', models.CharField(blank=True, max_length=20, verbose_name='Número WhatsApp')),
                ('alertar_contratos', models.BooleanField(default=True, verbose_name='Alertar vencimiento contratos')),
                ('alertar_pactos', models.BooleanField(default=True, verbose_name='Alertar vencimiento pactos HE')),
                ('alertar_parametros', models.BooleanField(default=True, verbose_name='Alertar cambios parámetros')),
                ('dias_anticipacion', models.PositiveIntegerField(default=7, verbose_name='Días anticipación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alerta_config', to='calculo_sueldo.empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Alertas',
                'verbose_name_plural': 'Configuraciones de Alertas',
            },
        ),
    ]
