# Generated by Django 6.0.6 on 2026-06-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo_sueldo', '0005_alerta_alertaconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoPrevisional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_trabajador', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombres', models.CharField(blank=True, max_length=255, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=255, verbose_name='Apellidos')),
                ('afp', models.CharField(blank=True, max_length=255, verbose_name='AFP')),
                ('fecha_afiliacion', models.DateField(blank=True, null=True, verbose_name='Fecha afiliación AFP')),
                ('estado', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('tipo', models.CharField(blank=True, max_length=100, verbose_name='Tipo trabajador')),
                ('fecha_consulta', models.DateTimeField(auto_now=True, verbose_name='Última consulta')),
            ],
            options={
                'verbose_name': 'Dato Previsional',
                'verbose_name_plural': 'Datos Previsionales',
            },
        ),
    ]
