# Generated by Django 6.0.6 on 2026-06-30 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo_sueldo', '0006_datoprevisional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finiquito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_termino', models.DateField(verbose_name='Fecha de término')),
                ('causal', models.CharField(choices=[('mutuo_acuerdo', 'Mutuo acuerdo (Art.159 N°1)'), ('renuncia', 'Renuncia del trabajador (Art.159 N°2)'), ('muerte', 'Muerte del trabajador (Art.159 N°3)'), ('vencimiento_plazo', 'Vencimiento del plazo (Art.159 N°4)'), ('conclusion_faena', 'Conclusión de la faena (Art.159 N°5)'), ('necesidades_empresa', 'Necesidades de la empresa (Art.161)'), ('despido_indirecto', 'Autodespido (Art.171)')], max_length=30, verbose_name='Causal')),
                ('aviso_previo', models.BooleanField(default=False, verbose_name='Aviso previo 30 días')),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sueldo base $')),
                ('dias_trabajados', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Días trabajados última quincena')),
                ('indemn_aviso_previo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Indemn. aviso previo $')),
                ('indemn_anios_servicio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Indemn. años servicio $')),
                ('anios_servicio', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Años de servicio')),
                ('sueldos_pendientes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sueldos pendientes $')),
                ('feriado_proporcional', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Feriado proporcional $')),
                ('horas_extra_pendientes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Horas extra pendientes $')),
                ('otros_bonos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros bonos/pagos $')),
                ('total_haberes', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total haberes $')),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuentos $')),
                ('liquido', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Líquido a pagar $')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('pdf_generado', models.TextField(blank=True, verbose_name='PDF (base64)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finiquitos', to='calculo_sueldo.contrato')),
            ],
            options={
                'verbose_name': 'Finiquito',
                'verbose_name_plural': 'Finiquitos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(verbose_name='Período')),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sueldo base $')),
                ('colacion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Colación $')),
                ('movilizacion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Movilización $')),
                ('horas_extra_cantidad', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Horas extra (cantidad)')),
                ('horas_extra_valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Horas extra $')),
                ('total_imponible', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total imponible $')),
                ('descuento_afp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Desc. AFP $')),
                ('descuento_salud', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Desc. Salud $')),
                ('descuento_seg_ces', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desc. Seg. Cesantía $')),
                ('descuento_iu', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impuesto Único $')),
                ('total_descuentos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total descuentos $')),
                ('liquido', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Líquido a pagar $')),
                ('costo_empleador', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo empleador $')),
                ('pdf_generado', models.TextField(blank=True, verbose_name='PDF (base64)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='calculo_sueldo.contrato')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'ordering': ['-periodo', '-created_at'],
                'unique_together': {('contrato', 'periodo')},
            },
        ),
    ]
