# Generated by Django 6.0.6 on 2026-06-30 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo_sueldo', '0007_finiquito_liquidacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='Año comercial')),
                ('dias_correspondientes', models.DecimalField(decimal_places=1, default=15, max_digits=4, verbose_name='Días hábiles correspondientes')),
                ('dias_pendientes_anterior', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Días pendientes año anterior')),
                ('dias_disfrutados', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Días disfrutados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='calculo_sueldo.contrato')),
            ],
            options={
                'verbose_name': 'Vacación',
                'verbose_name_plural': 'Vacaciones',
                'ordering': ['-anio'],
                'unique_together': {('contrato', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudVacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_termino', models.DateField(verbose_name='Fecha término')),
                ('dias_solicitados', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Días solicitados')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vacacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='calculo_sueldo.vacacion')),
            ],
            options={
                'verbose_name': 'Solicitud de Vacación',
                'verbose_name_plural': 'Solicitudes de Vacaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
